
clear all
close all
% Load data
load('Freud_Processed_BDIAT.mat');
X = exp(XF);
G = active_score;

% Recommended: block ACF only
out = Freud_Autocorr_Engine(X, G, ...
    'DoTrialACF', false, 'DoBlockACF', true, ...
    'MaxLagBlock', 8, 'BlockSummary', 'median', 'DetrendBlocks', true,'UseLog',false);

% % If you want to also see trial-level ACF (usually dominated by inertia)
% out2 = acf_trial_vs_block_with_plots(X, G, ...
%     'DoTrialACF', true, 'MaxLagTrial', 120, ...
%     'DoBlockACF', true, 'MaxLagBlock', 10);


out = Freud_Autocorr_Advanced(X, G, ...
    'MaxLagBlock', 8, ...
    'RhythmMaxLag', 8, ...
    'NumPerm', 10000, ...
    'NumShufflePreserve', 10000, ...
    'NumShuffleDestroy', 10000, ...
    'ShuffleDestroyMode', 'permuteBlocks', ...
    'FigureNamePrefix', 'MyTask','BlockSummary', 'mean');
